apiVersion: v1
kind: Service
metadata:
  name: app-redis
  namespace: app
  labels:
    app: app-redis
spec:
  selector:
    app: app-redis
  ports:
    - port: 6379
      targetPort: 6379
  type: ClusterIP
