apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cms-minio
  namespace: cms-prod
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 50Gi
