apiVersion: v1
kind: Service
metadata:
  name: app-mysql
  namespace: app
  labels:
    app: app-mysql
spec:
  selector:
    app: app-mysql
  ports:
    - port: 3306
      targetPort: 3306
  type: ClusterIP
  clusterIP: None  # headless for StatefulSet DNS
