#!/usr/bin/env bash
# =============================================================================
# k3s Uninstall Helper
#
# This is a thin safety wrapper around the uninstall scripts generated by the
# official k3s installer on the server:
#   - /usr/local/bin/k3s-uninstall.sh
#   - /usr/local/bin/k3s-agent-uninstall.sh
#
# It does not vendor those generated scripts into the repo. It only verifies the
# target and then runs the right server-side script locally or over SSH.
#
# Usage:
#   ./k8s/uninstall.sh --host deployer@1.2.3.4 --yes
#   ./k8s/uninstall.sh --host app --yes
#   ./k8s/uninstall.sh --local --yes
#   ./k8s/uninstall.sh --host app --agent --yes
# =============================================================================

set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
BOLD='\033[1m'
NC='\033[0m'

info() { echo -e "${BLUE}[INFO]${NC} $*"; }
ok() { echo -e "${GREEN}[OK]${NC} $*"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $*"; }
error() { echo -e "${RED}[ERROR]${NC} $*" >&2; }

usage() {
  cat <<'EOF'
Usage:
  k8s/uninstall.sh --host <ssh-host> --yes [--agent]
  k8s/uninstall.sh --local --yes [--agent]

Options:
  --host <ssh-host>  Run uninstall over SSH, e.g. deployer@1.2.3.4 or SSH alias app.
  --local            Run uninstall on the current machine.
  --agent            Use k3s-agent-uninstall.sh instead of k3s-uninstall.sh.
  --yes              Required confirmation for this destructive operation.
  -h, --help         Show this help.

This removes k3s cluster state from the target server. Back up databases,
uploads, secrets, and kubeconfig before running it.
EOF
}

TARGET_HOST=""
LOCAL=0
AGENT=0
YES=0

while [ "$#" -gt 0 ]; do
  case "$1" in
    --host)
      TARGET_HOST="${2:-}"
      shift 2
      ;;
    --local)
      LOCAL=1
      shift
      ;;
    --agent)
      AGENT=1
      shift
      ;;
    --yes)
      YES=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      error "Unknown argument: $1"
      usage
      exit 1
      ;;
  esac
done

if [ "$YES" -ne 1 ]; then
  error "Refusing to run without --yes."
  usage
  exit 1
fi

if [ "$LOCAL" -eq 1 ] && [ -n "$TARGET_HOST" ]; then
  error "Use either --local or --host, not both."
  exit 1
fi

if [ "$LOCAL" -ne 1 ] && [ -z "$TARGET_HOST" ]; then
  error "Missing target. Provide --host <ssh-host> or --local."
  usage
  exit 1
fi

if [ "$AGENT" -eq 1 ]; then
  UNINSTALL_SCRIPT="/usr/local/bin/k3s-agent-uninstall.sh"
else
  UNINSTALL_SCRIPT="/usr/local/bin/k3s-uninstall.sh"
fi

REMOTE_COMMAND=$(cat <<EOF
set -euo pipefail
echo "hostname=\$(hostname)"
echo "user=\$(whoami)"
if [ ! -x "${UNINSTALL_SCRIPT}" ]; then
  echo "Missing executable ${UNINSTALL_SCRIPT}" >&2
  exit 2
fi
sudo -n true
sudo "${UNINSTALL_SCRIPT}"
EOF
)

if [ "$LOCAL" -eq 1 ]; then
  warn "About to uninstall k3s on the current machine using ${UNINSTALL_SCRIPT}."
  bash -c "$REMOTE_COMMAND"
else
  warn "About to uninstall k3s on ${TARGET_HOST} using ${UNINSTALL_SCRIPT}."
  ssh "$TARGET_HOST" "$REMOTE_COMMAND"
fi

ok "k3s uninstall completed."
