apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cms-typesense-data
  namespace: cms-prod
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
