apiVersion: v1
kind: Service
metadata:
  name: cms-typesense
  namespace: cms-prod
  labels:
    app: cms-typesense
spec:
  selector:
    app: cms-typesense
  ports:
    - port: 8108
      targetPort: 8108
  type: ClusterIP
