apiVersion: v1
kind: Service
metadata:
  name: app-typesense
  namespace: app
  labels:
    app: app-typesense
spec:
  selector:
    app: app-typesense
  ports:
    - port: 8108
      targetPort: 8108
  type: ClusterIP
