<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\Theme;
use Illuminate\Database\Seeder;

class ThemeSeeder extends Seeder
{
    public function run(): void
    {
        $presets = [
            [
                'name' => 'Default',
                'slug' => 'default',
                'description' => 'Editorial storefront — indigo accent, Inter + Space Grotesk, flat radius.',
                'tokens' => [
                    'background' => '#ffffff',
                    'foreground' => '#0f172a',
                    'card' => '#ffffff',
                    'card-foreground' => '#0f172a',
                    'popover' => '#ffffff',
                    'popover-foreground' => '#0f172a',
                    'primary' => '#4f46e5',
                    'primary-foreground' => '#ffffff',
                    'secondary' => '#f1f5f9',
                    'secondary-foreground' => '#1e293b',
                    'muted' => '#f8fafc',
                    'muted-foreground' => '#64748b',
                    'accent' => '#eef2ff',
                    'accent-foreground' => '#312e81',
                    'destructive' => '#dc2626',
                    'destructive-foreground' => '#ffffff',
                    'border' => '#e2e8f0',
                    'input' => '#e2e8f0',
                    'ring' => '#4f46e5',
                    'chart-1' => '#4f46e5',
                    'chart-2' => '#06b6d4',
                    'chart-3' => '#10b981',
                    'chart-4' => '#f59e0b',
                    'chart-5' => '#ec4899',
                    'radius' => '0.375rem',
                ],
                'dark_tokens' => [
                    'background' => '#0f172a',
                    'foreground' => '#f8fafc',
                    'card' => '#1e293b',
                    'card-foreground' => '#f8fafc',
                    'popover' => '#1e293b',
                    'popover-foreground' => '#f8fafc',
                    'primary' => '#818cf8',
                    'primary-foreground' => '#0f172a',
                    'secondary' => '#1e293b',
                    'secondary-foreground' => '#f8fafc',
                    'muted' => '#1e293b',
                    'muted-foreground' => '#94a3b8',
                    'accent' => '#312e81',
                    'accent-foreground' => '#e0e7ff',
                    'destructive' => '#f87171',
                    'destructive-foreground' => '#0f172a',
                    'border' => '#334155',
                    'input' => '#334155',
                    'ring' => '#818cf8',
                    'radius' => '0.375rem',
                ],
                'typography' => [
                    'heading_font' => '"Space Grotesk", Inter, system-ui, sans-serif',
                    'body_font' => 'Inter, system-ui, sans-serif',
                    'base_size' => '16px',
                    'scale' => '1.25',
                    'h1_size' => '2.5rem',
                    'h2_size' => '2rem',
                    'h3_size' => '1.5rem',
                    'h4_size' => '1.25rem',
                ],
                    'heading' => [
                        'family' => 'Space Grotesk',
                        'source' => 'google',
                        'weights' => ['400', '500', '600', '700'],
                    ],
                    'body' => [
                        'family' => 'Inter',
                        'source' => 'google',
                        'weights' => ['400', '500', '600'],
                    ],
                ],
                'spacing' => [
                    'section_padding' => '5rem',
                    'block_gap' => '2rem',
                    'container_padding' => '1.5rem',
                ],
                'buttons' => [
                    'primary_border_radius' => '0.375rem',
                    'primary_padding_x' => '1.5rem',
                    'primary_padding_y' => '0.625rem',
                    'secondary_border_radius' => '0.375rem',
                    'secondary_padding_x' => '1.5rem',
                    'secondary_padding_y' => '0.625rem',
                ],
                'containers' => [
                    'max_width' => '80rem',
                    'content_width' => '48rem',
                    'narrow_width' => '40rem',
                ],
                'settings' => ['preset' => true, 'default_storefront' => true],
                'is_active' => true,
            ],
            [
                'name' => 'Slate Pro',
                'slug' => 'slate-pro',
                'description' => 'Professional indigo & dark slate — clean SaaS look.',
                'tokens' => [
                    'background' => '#f8fafc',
                    'foreground' => '#0f172a',
                    'card' => '#ffffff',
                    'card-foreground' => '#0f172a',
                    'popover' => '#ffffff',
                    'popover-foreground' => '#0f172a',
                    'primary' => '#4f46e5',
                    'primary-foreground' => '#ffffff',
                    'secondary' => '#e2e8f0',
                    'secondary-foreground' => '#1e293b',
                    'muted' => '#f1f5f9',
                    'muted-foreground' => '#64748b',
                    'accent' => '#e2e8f0',
                    'accent-foreground' => '#1e293b',
                    'destructive' => '#dc2626',
                    'destructive-foreground' => '#ffffff',
                    'border' => '#cbd5e1',
                    'input' => '#e2e8f0',
                    'ring' => '#4f46e5',
                    'chart-1' => '#6366f1',
                    'chart-2' => '#06b6d4',
                    'chart-3' => '#10b981',
                    'chart-4' => '#f59e0b',
                    'chart-5' => '#ec4899',
                    'radius' => '0.625rem',
                    'sidebar' => '#1e1b4b',
                    'sidebar-foreground' => '#e0e7ff',
                    'sidebar-primary' => '#818cf8',
                    'sidebar-primary-foreground' => '#1e1b4b',
                    'sidebar-accent' => '#312e81',
                    'sidebar-accent-foreground' => '#e0e7ff',
                    'sidebar-border' => '#312e81',
                    'sidebar-ring' => '#818cf8',
                ],
                'typography' => [
                    'heading_font' => 'Inter',
                    'body_font' => 'Inter',
                    'base_size' => '16px',
                    'scale' => '1.25',
                    'h1_size' => '2.5rem',
                    'h2_size' => '2rem',
                    'h3_size' => '1.5rem',
                    'h4_size' => '1.25rem',
                ],
                'spacing' => [
                    'section_padding' => '5rem',
                    'block_gap' => '2rem',
                    'container_padding' => '1.5rem',
                ],
                'buttons' => [
                    'primary_border_radius' => '0.5rem',
                    'primary_padding_x' => '1.5rem',
                    'primary_padding_y' => '0.75rem',
                    'secondary_border_radius' => '0.5rem',
                    'secondary_padding_x' => '1.5rem',
                    'secondary_padding_y' => '0.75rem',
                ],
                'containers' => [
                    'max_width' => '1280px',
                    'content_width' => '768px',
                    'narrow_width' => '640px',
                ],
                'settings' => ['preset' => true],
                'is_active' => false,
            ],
            [
                'name' => 'Emerald SaaS',
                'slug' => 'emerald-saas',
                'description' => 'Stripe-inspired emerald green with a deep forest sidebar.',
                'tokens' => [
                    'background' => '#f0fdf4',
                    'foreground' => '#052e16',
                    'card' => '#ffffff',
                    'card-foreground' => '#052e16',
                    'popover' => '#ffffff',
                    'popover-foreground' => '#052e16',
                    'primary' => '#059669',
                    'primary-foreground' => '#ffffff',
                    'secondary' => '#d1fae5',
                    'secondary-foreground' => '#064e3b',
                    'muted' => '#ecfdf5',
                    'muted-foreground' => '#047857',
                    'accent' => '#6ee7b7',
                    'accent-foreground' => '#064e3b',
                    'destructive' => '#dc2626',
                    'destructive-foreground' => '#ffffff',
                    'border' => '#a7f3d0',
                    'input' => '#d1fae5',
                    'ring' => '#059669',
                    'chart-1' => '#059669',
                    'chart-2' => '#06b6d4',
                    'chart-3' => '#6366f1',
                    'chart-4' => '#f59e0b',
                    'chart-5' => '#ec4899',
                    'radius' => '0.5rem',
                    'sidebar' => '#022c22',
                    'sidebar-foreground' => '#d1fae5',
                    'sidebar-primary' => '#34d399',
                    'sidebar-primary-foreground' => '#022c22',
                    'sidebar-accent' => '#064e3b',
                    'sidebar-accent-foreground' => '#d1fae5',
                    'sidebar-border' => '#065f46',
                    'sidebar-ring' => '#34d399',
                ],
                'typography' => [
                    'heading_font' => 'Inter',
                    'body_font' => 'Inter',
                    'base_size' => '16px',
                    'scale' => '1.25',
                    'h1_size' => '2.5rem',
                    'h2_size' => '2rem',
                    'h3_size' => '1.5rem',
                    'h4_size' => '1.25rem',
                ],
                'spacing' => [
                    'section_padding' => '5rem',
                    'block_gap' => '2rem',
                    'container_padding' => '1.5rem',
                ],
                'buttons' => [
                    'primary_border_radius' => '0.375rem',
                    'primary_padding_x' => '1.5rem',
                    'primary_padding_y' => '0.75rem',
                    'secondary_border_radius' => '0.375rem',
                    'secondary_padding_x' => '1.5rem',
                    'secondary_padding_y' => '0.75rem',
                ],
                'containers' => [
                    'max_width' => '1280px',
                    'content_width' => '768px',
                    'narrow_width' => '640px',
                ],
                'settings' => ['preset' => true],
                'is_active' => false,
            ],
            [
                'name' => 'Violet Studio',
                'slug' => 'violet-studio',
                'description' => 'Figma-inspired violet with a deep purple sidebar.',
                'tokens' => [
                    'background' => '#faf5ff',
                    'foreground' => '#2e1065',
                    'card' => '#ffffff',
                    'card-foreground' => '#2e1065',
                    'popover' => '#ffffff',
                    'popover-foreground' => '#2e1065',
                    'primary' => '#7c3aed',
                    'primary-foreground' => '#ffffff',
                    'secondary' => '#ede9fe',
                    'secondary-foreground' => '#4c1d95',
                    'muted' => '#f5f3ff',
                    'muted-foreground' => '#6d28d9',
                    'accent' => '#c4b5fd',
                    'accent-foreground' => '#4c1d95',
                    'destructive' => '#dc2626',
                    'destructive-foreground' => '#ffffff',
                    'border' => '#ddd6fe',
                    'input' => '#ede9fe',
                    'ring' => '#7c3aed',
                    'chart-1' => '#7c3aed',
                    'chart-2' => '#ec4899',
                    'chart-3' => '#06b6d4',
                    'chart-4' => '#10b981',
                    'chart-5' => '#f59e0b',
                    'radius' => '0.75rem',
                    'sidebar' => '#2e1065',
                    'sidebar-foreground' => '#f5f3ff',
                    'sidebar-primary' => '#a78bfa',
                    'sidebar-primary-foreground' => '#2e1065',
                    'sidebar-accent' => '#4c1d95',
                    'sidebar-accent-foreground' => '#f5f3ff',
                    'sidebar-border' => '#4c1d95',
                    'sidebar-ring' => '#a78bfa',
                ],
                'typography' => [
                    'heading_font' => 'Inter',
                    'body_font' => 'Inter',
                    'base_size' => '16px',
                    'scale' => '1.25',
                    'h1_size' => '2.5rem',
                    'h2_size' => '2rem',
                    'h3_size' => '1.5rem',
                    'h4_size' => '1.25rem',
                ],
                'spacing' => [
                    'section_padding' => '5rem',
                    'block_gap' => '2rem',
                    'container_padding' => '1.5rem',
                ],
                'buttons' => [
                    'primary_border_radius' => '0.75rem',
                    'primary_padding_x' => '1.5rem',
                    'primary_padding_y' => '0.75rem',
                    'secondary_border_radius' => '0.75rem',
                    'secondary_padding_x' => '1.5rem',
                    'secondary_padding_y' => '0.75rem',
                ],
                'containers' => [
                    'max_width' => '1280px',
                    'content_width' => '768px',
                    'narrow_width' => '640px',
                ],
                'settings' => ['preset' => true],
                'is_active' => false,
            ],
            [
                'name' => 'Midnight Blue',
                'slug' => 'midnight-blue',
                'description' => 'Deep corporate navy — GitLab / Jira energy.',
                'tokens' => [
                    'background' => '#f0f4ff',
                    'foreground' => '#0a0e2e',
                    'card' => '#ffffff',
                    'card-foreground' => '#0a0e2e',
                    'popover' => '#ffffff',
                    'popover-foreground' => '#0a0e2e',
                    'primary' => '#2563eb',
                    'primary-foreground' => '#ffffff',
                    'secondary' => '#dbeafe',
                    'secondary-foreground' => '#1e3a8a',
                    'muted' => '#eff6ff',
                    'muted-foreground' => '#3b82f6',
                    'accent' => '#93c5fd',
                    'accent-foreground' => '#1e3a8a',
                    'destructive' => '#dc2626',
                    'destructive-foreground' => '#ffffff',
                    'border' => '#bfdbfe',
                    'input' => '#dbeafe',
                    'ring' => '#2563eb',
                    'chart-1' => '#2563eb',
                    'chart-2' => '#06b6d4',
                    'chart-3' => '#10b981',
                    'chart-4' => '#f59e0b',
                    'chart-5' => '#ec4899',
                    'radius' => '0.5rem',
                    'sidebar' => '#0a0e2e',
                    'sidebar-foreground' => '#dbeafe',
                    'sidebar-primary' => '#60a5fa',
                    'sidebar-primary-foreground' => '#0a0e2e',
                    'sidebar-accent' => '#1e3a8a',
                    'sidebar-accent-foreground' => '#dbeafe',
                    'sidebar-border' => '#1e3a8a',
                    'sidebar-ring' => '#60a5fa',
                ],
                'typography' => [
                    'heading_font' => 'Inter',
                    'body_font' => 'Inter',
                    'base_size' => '16px',
                    'scale' => '1.25',
                    'h1_size' => '2.5rem',
                    'h2_size' => '2rem',
                    'h3_size' => '1.5rem',
                    'h4_size' => '1.25rem',
                ],
                'spacing' => [
                    'section_padding' => '5rem',
                    'block_gap' => '2rem',
                    'container_padding' => '1.5rem',
                ],
                'buttons' => [
                    'primary_border_radius' => '0.5rem',
                    'primary_padding_x' => '1.5rem',
                    'primary_padding_y' => '0.75rem',
                    'secondary_border_radius' => '0.5rem',
                    'secondary_padding_x' => '1.5rem',
                    'secondary_padding_y' => '0.75rem',
                ],
                'containers' => [
                    'max_width' => '1280px',
                    'content_width' => '768px',
                    'narrow_width' => '640px',
                ],
                'settings' => ['preset' => true],
                'is_active' => false,
            ],
            [
                'name' => 'Amber Commerce',
                'slug' => 'amber-commerce',
                'description' => 'Warm golden tones for e-commerce and marketing tools.',
                'tokens' => [
                    'background' => '#fefce8',
                    'foreground' => '#1c1004',
                    'card' => '#ffffff',
                    'card-foreground' => '#1c1004',
                    'popover' => '#ffffff',
                    'popover-foreground' => '#1c1004',
                    'primary' => '#d97706',
                    'primary-foreground' => '#ffffff',
                    'secondary' => '#fef3c7',
                    'secondary-foreground' => '#78350f',
                    'muted' => '#fef9c3',
                    'muted-foreground' => '#92400e',
                    'accent' => '#fbbf24',
                    'accent-foreground' => '#78350f',
                    'destructive' => '#dc2626',
                    'destructive-foreground' => '#ffffff',
                    'border' => '#fde68a',
                    'input' => '#fef3c7',
                    'ring' => '#d97706',
                    'chart-1' => '#d97706',
                    'chart-2' => '#ef4444',
                    'chart-3' => '#10b981',
                    'chart-4' => '#8b5cf6',
                    'chart-5' => '#06b6d4',
                    'radius' => '0.75rem',
                    'sidebar' => '#1c1004',
                    'sidebar-foreground' => '#fef3c7',
                    'sidebar-primary' => '#fbbf24',
                    'sidebar-primary-foreground' => '#1c1004',
                    'sidebar-accent' => '#78350f',
                    'sidebar-accent-foreground' => '#fef3c7',
                    'sidebar-border' => '#92400e',
                    'sidebar-ring' => '#fbbf24',
                ],
                'typography' => [
                    'heading_font' => 'Inter',
                    'body_font' => 'Inter',
                    'base_size' => '16px',
                    'scale' => '1.25',
                    'h1_size' => '2.5rem',
                    'h2_size' => '2rem',
                    'h3_size' => '1.5rem',
                    'h4_size' => '1.25rem',
                ],
                'spacing' => [
                    'section_padding' => '5rem',
                    'block_gap' => '2rem',
                    'container_padding' => '1.5rem',
                ],
                'buttons' => [
                    'primary_border_radius' => '0.75rem',
                    'primary_padding_x' => '1.5rem',
                    'primary_padding_y' => '0.75rem',
                    'secondary_border_radius' => '0.75rem',
                    'secondary_padding_x' => '1.5rem',
                    'secondary_padding_y' => '0.75rem',
                ],
                'containers' => [
                    'max_width' => '1280px',
                    'content_width' => '768px',
                    'narrow_width' => '640px',
                ],
                'settings' => ['preset' => true],
                'is_active' => false,
            ],
            [
                'name' => 'Glassmorphism',
                'slug' => 'glassmorphism',
                'description' => 'Frosted glass — translucent cards and sidebar with backdrop blur.',
                'tokens' => [
                    'background' => '#bfdbfe',
                    'foreground' => '#1e3a8a',
                    'card' => '#ffffff',
                    'card-foreground' => '#1e3a8a',
                    'popover' => '#ffffff',
                    'popover-foreground' => '#1e3a8a',
                    'primary' => '#2563eb',
                    'primary-foreground' => '#ffffff',
                    'secondary' => '#dbeafe',
                    'secondary-foreground' => '#1e40af',
                    'muted' => '#eff6ff',
                    'muted-foreground' => '#3b82f6',
                    'accent' => '#93c5fd',
                    'accent-foreground' => '#1e3a8a',
                    'destructive' => '#dc2626',
                    'destructive-foreground' => '#ffffff',
                    'border' => 'rgba(255, 255, 255, 0.5)',
                    'input' => 'rgba(255, 255, 255, 0.6)',
                    'ring' => '#3b82f6',
                    'chart-1' => '#2563eb',
                    'chart-2' => '#7c3aed',
                    'chart-3' => '#059669',
                    'chart-4' => '#d97706',
                    'chart-5' => '#dc2626',
                    'radius' => '0.75rem',
                    'sidebar' => '#1e40af',
                    'sidebar-foreground' => '#dbeafe',
                    'sidebar-primary' => '#93c5fd',
                    'sidebar-primary-foreground' => '#1e3a8a',
                    'sidebar-accent' => '#1d4ed8',
                    'sidebar-accent-foreground' => '#dbeafe',
                    'sidebar-border' => 'rgba(147, 197, 253, 0.3)',
                    'sidebar-ring' => '#60a5fa',
                ],
                'typography' => [
                    'heading_font' => 'Inter',
                    'body_font' => 'Inter',
                    'base_size' => '16px',
                    'scale' => '1.25',
                    'h1_size' => '2.5rem',
                    'h2_size' => '2rem',
                    'h3_size' => '1.5rem',
                    'h4_size' => '1.25rem',
                ],
                'spacing' => [
                    'section_padding' => '5rem',
                    'block_gap' => '2rem',
                    'container_padding' => '1.5rem',
                ],
                'buttons' => [
                    'primary_border_radius' => '0.75rem',
                    'primary_padding_x' => '1.5rem',
                    'primary_padding_y' => '0.75rem',
                    'secondary_border_radius' => '0.75rem',
                    'secondary_padding_x' => '1.5rem',
                    'secondary_padding_y' => '0.75rem',
                ],
                'containers' => [
                    'max_width' => '1280px',
                    'content_width' => '768px',
                    'narrow_width' => '640px',
                ],
                'settings' => ['preset' => true],
                'is_active' => false,
            ],
            [
                'name' => 'Rose Admin',
                'slug' => 'rose-admin',
                'description' => 'Bold rose pink — modern Clerk / Resend aesthetic.',
                'tokens' => [
                    'background' => '#fff1f2',
                    'foreground' => '#1c0a10',
                    'card' => '#ffffff',
                    'card-foreground' => '#1c0a10',
                    'popover' => '#ffffff',
                    'popover-foreground' => '#1c0a10',
                    'primary' => '#e11d48',
                    'primary-foreground' => '#ffffff',
                    'secondary' => '#ffe4e6',
                    'secondary-foreground' => '#881337',
                    'muted' => '#fff1f2',
                    'muted-foreground' => '#9f1239',
                    'accent' => '#fda4af',
                    'accent-foreground' => '#881337',
                    'destructive' => '#dc2626',
                    'destructive-foreground' => '#ffffff',
                    'border' => '#fecdd3',
                    'input' => '#ffe4e6',
                    'ring' => '#e11d48',
                    'chart-1' => '#e11d48',
                    'chart-2' => '#f97316',
                    'chart-3' => '#8b5cf6',
                    'chart-4' => '#06b6d4',
                    'chart-5' => '#10b981',
                    'radius' => '0.75rem',
                    'sidebar' => '#1c0a10',
                    'sidebar-foreground' => '#ffe4e6',
                    'sidebar-primary' => '#fb7185',
                    'sidebar-primary-foreground' => '#1c0a10',
                    'sidebar-accent' => '#881337',
                    'sidebar-accent-foreground' => '#ffe4e6',
                    'sidebar-border' => '#9f1239',
                    'sidebar-ring' => '#fb7185',
                ],
                'typography' => [
                    'heading_font' => 'Inter',
                    'body_font' => 'Inter',
                    'base_size' => '16px',
                    'scale' => '1.25',
                    'h1_size' => '2.5rem',
                    'h2_size' => '2rem',
                    'h3_size' => '1.5rem',
                    'h4_size' => '1.25rem',
                ],
                'spacing' => [
                    'section_padding' => '5rem',
                    'block_gap' => '2rem',
                    'container_padding' => '1.5rem',
                ],
                'buttons' => [
                    'primary_border_radius' => '0.75rem',
                    'primary_padding_x' => '1.5rem',
                    'primary_padding_y' => '0.75rem',
                    'secondary_border_radius' => '0.75rem',
                    'secondary_padding_x' => '1.5rem',
                    'secondary_padding_y' => '0.75rem',
                ],
                'containers' => [
                    'max_width' => '1280px',
                    'content_width' => '768px',
                    'narrow_width' => '640px',
                ],
                'settings' => ['preset' => true],
                'is_active' => false,
            ],
        ];

        $newSlugs = collect($presets)->pluck('slug');

        Theme::query()
            ->whereJsonContains('settings->preset', true)
            ->whereNotIn('slug', $newSlugs)
            ->delete();

        Theme::query()
            ->whereIn('slug', $newSlugs)
            ->update(['is_active' => false]);

        $hasActiveTheme = Theme::query()->where('is_active', true)->exists();

        foreach ($presets as $preset) {
            $isActive = $preset['is_active'] ?? false;
            if (! $hasActiveTheme && ($preset['settings']['default_storefront'] ?? false)) {
                $isActive = true;
                $hasActiveTheme = true;
            }

            Theme::query()->updateOrCreate(
                ['slug' => $preset['slug']],
                [
                    'name' => $preset['name'],
                    'description' => $preset['description'],
                    'tokens' => $preset['tokens'],
                    'dark_tokens' => $preset['dark_tokens'] ?? null,
                    'typography' => $preset['typography'],
                    'spacing' => $preset['spacing'],
                    'buttons' => $preset['buttons'],
                    'containers' => $preset['containers'],
                    'settings' => $preset['settings'],
                    'is_active' => $isActive,
                ]
            );
        }
    }
}
