apiVersion: v1
kind: Service
metadata:
  name: app-server
  namespace: app
  labels:
    app: app-server
spec:
  selector:
    app: app-server
    component: web
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP
